name: Upload booking.js to Supabase

on:
  push:
    branches: [main]  # or change to 'master' if that's your branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Supabase Storage
        run: |
          curl -X POST "$SUPABASE_URL/storage/v1/object/scripts/booking.js" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/javascript" \
            --data-binary @booking.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
